services:
  app:
    depends_on:
      redis:
        condition: service_healthy

    environment:
      REDIS_URL: redis://:${REDIS_PASSWORD:-supersecure}@redis

      # empty to use redis mock for testing
      REDIS_TEST_URL: redis://:${REDIS_PASSWORD:-supersecure}@redis

  redis:
    image: redis/redis-stack-server:latest # freeze for prod

    # restart: unless-stopped

    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD:-supersecure}"

    healthcheck:
      test: "redis-cli --raw incr ping"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 0s

